/*
 * generated by Xtext
 */
package com.github.thomasfischl.rayden;

import com.github.thomasfischl.rayden.formatting.RaydenFormatter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RaydenDSLRuntimeModule extends com.github.thomasfischl.rayden.AbstractRaydenDSLRuntimeModule {

  @Override
  public Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
    return RaydenFormatter.class;
  }

}
