/*
* generated by Xtext
*/
package com.github.thomasfischl.rayden;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RaydenDSLStandaloneSetup extends RaydenDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new RaydenDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

